<?php
	echo "This is addslashes function<br>";
		$str = "Hi', my name is 'Mehul";
		echo addslashes($str);
	echo "<br>";
	echo "<br>This is chr function<br>";
		echo chr(82);
	echo "<br>";
	echo "<br>This is chunk_split function";
		$str = "I'm learning Web Application";
	echo "<br>";
		echo chunk_split($str,1,"-");
	echo "<br>";
	echo "<br>This is count_chars function";
	echo "<br>Will show which characters are used in 'I'M A NJIT STUDENT'";
	echo "<br>";
		$str = "i'm an njit student";
		echo count_chars($str,3);
	echo "<br><br>";
	echo "This is echo function";
		$str = "Currently Junior";
		echo "<br>".$str;
	echo "<br><br>";
	echo "This is explode function";
		$str = "It's a rainy day today";
	echo "<br>";
		print_r (explode(" ",$str));
	echo "<br><br>";
	echo "This is htmlentities function";
		$str = "I'm not 'sure' about this";
	echo "<br>";
		echo htmlentities($str,ENT_QUOTES);
	echo "<br><br>";
	echo "This is htmlspecialchars_decode function";
		$str = 'I want to &quot;LEARN&quot;.';
	echo "<br>";
		echo htmlspecialchars_decode($str, ENT_QUOTES);
	echo "<br><br>";		
	echo "This is implode function";
		$arr = array('This','is','an amazing','work');
	echo "<br>";	
		echo implode("~",$arr);
	echo "<br><br>";
	echo "This is md5 function";
		$str = "Mehul Rana";
		echo "<br>".md5($str);
	echo "<br><br>";
	echo "This is rtrim function";
	echo "<br>";
		$str = "The name will be removed: Mehul";
		echo $str . "<br>";
		echo rtrim($str,"Mehul");
	echo "<br><br>";
	echo "This is str_getcsv function";
		
	echo "<br><br>";
	echo "This is strip_tags function";
	echo "<br>";
		echo "Hey <b>There!</b>", "<br>";
		echo strip_tags("Hey <b>There!</b>"),"<br>";
		echo "the &lt;b&gt; tags get stip";
	echo "<br><br>";
	echo "This is strpos function";
	echo "<br>";
		$str = "the word house is on which postion =";
		echo $str;
		echo strpos($str,"house");
	echo "<br><br>";
	echo "This is string length function";
	echo "<br>";
		$str = "The lenght of this string is =";
		echo $str;
		echo strlen($str);	
?>
